/**
 * The 12-Script Starter Kit. Every new operator gets these — the game is
 * fully playable from minute one, across all 7 categories.
 */
import type { ScriptDef } from "./index.js";

export const STARTER_SCRIPTS: ScriptDef[] = [
  {
    id: "pulse-jab",
    name: "Pulse Jab",
    category: "strike",
    element: "null",
    tags: ["EDGE"],
    rarity: "spark",
    description: "A quick data-fist. Nothing fancy — it lands.",
    effect: { kind: "damage", power: 12, range: "melee" },
  },
  {
    id: "cinder-slash",
    name: "Cinder Slash",
    category: "strike",
    element: "fire",
    tags: ["EDGE", "BLAZE"],
    rarity: "spark",
    description: "A blazing sword arc that leaves a burning trail.",
    effect: { kind: "damage", power: 22, range: "melee" },
  },
  {
    id: "arc-lance",
    name: "Arc Lance",
    category: "strike",
    element: "elec",
    tags: ["PIERCE"],
    rarity: "ember",
    description: "A piercing bolt that overflows through lined-up targets.",
    effect: { kind: "damage", power: 18, range: "mid" },
  },
  {
    id: "aegis-wall",
    name: "Aegis Wall",
    category: "ward",
    element: "null",
    tags: ["GUARD"],
    rarity: "spark",
    description: "A hard-light barrier. Holds for one solid hit.",
    effect: { kind: "barrier", power: 30, range: "melee" },
  },
  {
    id: "mend-protocol",
    name: "Mend Protocol",
    category: "ward",
    element: "aqua",
    tags: ["GUARD", "TIDE"],
    rarity: "spark",
    description: "Knits damaged sectors back together. Slow, warm, reliable.",
    effect: { kind: "heal", power: 25, range: "melee" },
  },
  {
    id: "ghostphase",
    name: "Ghostphase",
    category: "ward",
    element: "null",
    tags: ["GUARD"],
    rarity: "ember",
    description: "Brief intangibility. The hit passes through like weather.",
    effect: { kind: "phase", power: 0, range: "melee" },
  },
  {
    id: "static-snare",
    name: "Static Snare",
    category: "trick",
    element: "elec",
    tags: ["SNARE"],
    rarity: "spark",
    description: "Locks a target's joints with crawling static.",
    effect: { kind: "stun", power: 0, range: "mid" },
  },
  {
    id: "deep-scan",
    name: "Deep Scan",
    category: "trick",
    element: "null",
    tags: ["SNARE"],
    rarity: "spark",
    description: "Reads a target's element and intent. Knowledge is a weapon.",
    effect: { kind: "stun", power: 0, range: "long" },
  },
  {
    id: "overclock",
    name: "Overclock",
    category: "surge",
    element: "elec",
    tags: ["SURGE"],
    rarity: "spark",
    description: "Redlines the agent's actuators. Faster everything, briefly.",
    effect: { kind: "buff", power: 0, range: "melee" },
  },
  {
    id: "amplify",
    name: "Amplify",
    category: "surge",
    element: "null",
    tags: ["SURGE", "EDGE"],
    rarity: "ember",
    description: "Turns the next strike up past its rated limit.",
    effect: { kind: "buff", power: 0, range: "melee" },
  },
  {
    id: "echo-call",
    name: "Echo Call",
    category: "summon",
    element: "null",
    tags: ["CALL"],
    rarity: "ember",
    description: "Summons a friendly data-echo to fight beside the agent.",
    effect: { kind: "summon", power: 20, range: "mid" },
  },
  {
    id: "scorch-field",
    name: "Scorch Field",
    category: "terrain",
    element: "fire",
    tags: ["BLAZE"],
    rarity: "ember",
    description: "Rewrites the ground into burning sectors. Mind the floor.",
    effect: { kind: "terrain", power: 8, range: "mid" },
  },
];
